### ISSUE TITLE
1 column on mobile

### ISSUE THREAD

**Issue by winstonford** [mandiwise/isotope-posts#16]
Hi Mandi,

Excellent plug-in. I am trying to have the isotope view go from three columns on a wide display to one column on mobile, just like in this site here http://shaylalove.net/?page_id=426 

This is my site http://winstonford.com

Any tips?  Thanks!

**Comment by winstonford** [comment]
In case anyone else is on the path, I added rules below to my css and it looks ok:

#iso-loop li {
	width: 100%;
}

@media all and (min-width: 480px) {
	#iso-loop li {
		width: 30.5%;
	}
}

**Comment by mandiwise** [comment]
Glad you were able to sort this out, thanks for posting your solution.
