### ISSUE TITLE
modify to fade, not hide, filtered posts?

### ISSUE THREAD

**Issue by wordfool** [mandiwise/isotope-posts#18]
Thanks for the great plugin... does exactly what I was looking for without any bloat. One minor modification I have attempted and failed at, however, is to have the filtered posts fade in place and not disappear (I'm using it for lists of post titles rather than titles+excerpts). I'm after the same effect as illustrated in David Desandro's example here: http://codepen.io/desandro/pen/drpJK/

I've tried adding the new hiddenStyle and visibleStyle to your code but there's something else apparently going on because they don't work as they should (items fade as per the new hiddenStyle attribute, but then disappear). Here's what I tried:

		var $container = $('#iso-loop').imagesLoaded( function () {
			$container.fadeIn().isotope({
				itemSelector : '.iso-post',
				layoutMode : iso_vars.iso_layout,
				filter : initialFilter,
				hiddenStyle: {
				  opacity: 0.5
				},
				visibleStyle: {
				  opacity: 1
				}			
			});
		});

**Comment by mandiwise** [comment]
Apologies for the delay of my response. Not sure if you figured this out, but unfortunately this customization is a little outside the scope of what I can provide for free support with this plugin right now.
