### ISSUE TITLE
Not working in WP Static Homepage

### ISSUE THREAD

**Issue by sigmadan** [mandiwise/isotope-posts#20]
Hi Mandi-

I have downloaded the zip, and when I put it on my server and activate it, it activates.  I have made a shortcode and put it on my static homepage, but no posts are showing up.  After some head scratching, I noticed public/assets/css/public.css has a #iso-loop {display: none}.  I delete that, and the posts show up, but when I select a filter they don't move or anything.  Also, when I hit See All filter, it brings me back up to the top of the page, as if your changes for 2.0.9 didn't work at all.  My site is at http://dan-alisha.com.  

I'm puzzled because I have this working successfully on another site.  I have it working correctly at http://blog.sigmabeauty.com

Out of curiosity, I also tried downloading it with git vs downloading the zip.  It made no difference, except the package downloaded through git had the folder named isotope-posts, vs isotope-posts-master when downloaded as zip.

Thanks so much for any and all help with this.

**Comment by sigmadan** [comment]
I think I found the main problem.  Inline styles are not being dynamically added to the <ul id="iso-loop"> or the <li class="iso-post"> elements.  Does this mean jQuery or JavaScript is not being loaded properly?

**Comment by mandiwise** [comment]
Can you confirm that the directory you currently have uploaded to your plugins folder in fact has "-master" removed from the name as per the [installation instructions](https://github.com/mandiwise/isotope-posts#installation)?

**Comment by sigmadan** [comment]
I have confirmed.  My folder was named "isotope-posts-master" but is now named "isotope-posts" and the problem persists.  I'm thinking its a jQuery or JS problem, as I noticed the inline styles aren't being dynamically added to iso-loop and iso-post elements.  I'm not too familiar with how to diagnose jQuery problems.  I have jQuery version 1.11.1 working successfully on other elements on the page.  Can you confirm what version of the jQuery library is required for this plugin (if any)?

**Comment by mandiwise** [comment]
That version of jQuery will be fine. I looked at your site and there's a script that loads from your theme (before Isotope) that is throwing an error in the console, and it may be blocking the Isotope JS files from doing what they need to do. I think you best bet is try debugging that error in your theme first and see if that helps.

**Comment by sigmadan** [comment]
Thanks for the suggestion Mandi!  I commented that line out in the theme JS and it is working now.
